- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Kubernetes API service
  ansible.builtin.systemd:
    state: restarted
    name: kubernetes-api.service
  listen: kubernetes api daemon-restart
  timeout: 15
  throttle: 1

- name: Restart Kubernetes Controller Manager service
  ansible.builtin.systemd:
    state: restarted
    name: kubernetes-controller-manager.service
  listen: kubernetes controller-manager daemon-restart
  timeout: 15
  throttle: 1

- name: Restart Kubernetes Scheduler service
  ansible.builtin.systemd:
    state: restarted
    name: kubernetes-scheduler.service
  listen: kubernetes scheduler daemon-restart
  timeout: 15
  throttle: 1

- name: Restart Kubelet service
  ansible.builtin.systemd:
    state: restarted
    name: kubelet.service
  listen: kubernetes kubelet daemon-restart
  timeout: 15
  throttle: 1

- name: Restart Kubernetes Proxy service
  ansible.builtin.systemd:
    state: restarted
    name: kubernetes-proxy.service
  listen: kubernetes proxy daemon-restart
  timeout: 15
  throttle: 1
