etcd_version: "3.5.19"
etcd_conf_dir: /etc/etcd
etcd_data_dir: /var/lib/etcd
etcd_cluster_name: kubernetes

etcd_uid: 65311
etcd_gid: 65311

# you may need to update these settings depending on how large
# is your cluster
etcd_restart_timeout: 30

# usage: {{ machine_arch_map[ansible_architecture] }}
machine_arch_map:
  aarch64: arm64
  arm64: arm64
  x86_64: amd64
  amd64: amd64

etcd_force_upgrade: "{{ force_upgrade | default(false) }}"
